### ISSUE TITLE
Start Learning Button hover glow + recentering of copyright

### ISSUE THREAD

**Issue by the3plet** [One-Language/Website#130]
+ Adding hover glow to the button will give much cleaner look
  current button state:
  ![image](https://user-images.githubusercontent.com/88719525/197391278-45a9f2a8-863a-44c5-b369-75205a12fdbd.png)

+ Copyright text not seems to be aligned
![image](https://user-images.githubusercontent.com/88719525/197391345-4aeb6c9a-fe8b-4c0c-b27f-c41b271c75c4.png)

**Comment by the3plet** [comment]
@jbampton @BaseMax  can you please assign me, i can help out

**Comment by jbampton** [comment]
Hey @the3plet you are now assigned.  Thanks 💯

**Comment by jbampton** [comment]
Current site is deployed from the `alpha-version` branch

<img width="868" alt="Screen Shot 2022-10-24 at 12 20 30 am" src="https://user-images.githubusercontent.com/418747/197397382-1f8ebcad-2e6e-4775-8014-418bf0376277.png">

<img width="512" alt="Screen Shot 2022-10-24 at 12 20 45 am" src="https://user-images.githubusercontent.com/418747/197397377-7cb0e32b-b6db-4731-871b-4aabbfffb68b.png">

**Comment by the3plet** [comment]
so i should be cloning alpha branch right?

**Comment by jbampton** [comment]
Sorry about the confusion.

We are using FTP to deploy the `main` branch to our own service provider.

The old site is on alpha-version.

So please work on the `main` branch

**Comment by BaseMax** [comment]
Currently, the **main** branch is active and deployed on onelang.org
so in this case, if you want to fix that bug you need to clone and send PR to that branch.

Keep calm and love programming. happy hacktoberfest

**Comment by the3plet** [comment]
Okey🥂

**Comment by BaseMax** [comment]
Welcome.

Our GitHub actions are defined for the main branch. so I am right. the main branch is active now.
https://github.com/One-Language/Website/blob/main/.github/workflows/deploy.yml
```
on:
  push:
    branches:
      - main
```

**Comment by jbampton** [comment]
Ah yes that was my addition today :)

And I still got mixed up
