### ISSUE TITLE
[BUG] qs vulnerable to Prototype Pollution #36

### ISSUE THREAD

**Issue by BaseMax** [One-Language/Website#150]
https://github.com/One-Language/Website/security/dependabot/36

Dependabot cannot update to the required version
One or more other dependencies require a version that is incompatible with this update.

Package
Affected versions

Patched version
qs

(npm)
>= 6.5.0, < 6.5.3
6.5.3

qs before 6.10.3, as used in Express before 4.17.3 and other products, allows attackers to cause a Node process hang for an Express application because an __ proto__ key can be used. In many typical Express use cases, an unauthenticated remote attacker can place the attack payload in the query string of the URL that is used to visit the application, such as a[proto]=b&a[proto]&a[length]=100000000. The fix was backported to qs 6.9.7, 6.8.3, 6.7.3, 6.6.1, 6.5.3, 6.4.1, 6.3.3, and 6.2.4 (and therefore Express 4.17.3, which has "deps: qs@6.9.7" in its release description, is not vulnerable).

**Comment by jbampton** [comment]
Fixed in #151 

https://github.com/One-Language/Website/security/dependabot/36
