### ISSUE TITLE
[BUG]:  Re-add all the files we need that were deleted

### ISSUE THREAD

**Issue by jbampton** [One-Language/Website#32]
**Describe the bug**

Most of the files we needed have been deleted.

https://github.com/One-Language/Website/pull/29
 
**Screenshots**

<img width="623" alt="Screen Shot 2021-05-30 at 11 07 48 pm" src="https://user-images.githubusercontent.com/418747/120105442-3e58d480-c19c-11eb-8ff6-f4df128ebf6b.png">

And others

**Comment by async-costelo** [comment]
@jbampton kindly close. Thanks!
