### ISSUE TITLE
Broken links on website

### ISSUE THREAD

**Issue by jbampton** [One-Language/Website#4]
Click on "FA" or "Asrez" and both links are broken.

![Screen Shot 2020-11-28 at 1 51 01 pm](https://user-images.githubusercontent.com/418747/100493257-1357de80-3181-11eb-9926-f0c5adc90507.png)

![Screen Shot 2020-11-28 at 1 51 18 pm](https://user-images.githubusercontent.com/418747/100493270-279bdb80-3181-11eb-819f-719be9dc2187.png)

![Screen Shot 2020-11-28 at 1 52 20 pm](https://user-images.githubusercontent.com/418747/100493272-2b2f6280-3181-11eb-9cf8-73d68c9817a8.png)

**Comment by BaseMax** [comment]
Hey;
 are you sure? onelang.ir is available..

**Comment by jbampton** [comment]
This issue was from November last year

**Comment by BaseMax** [comment]
Oh, Nov 28, 2020
Sorry i see this message today.
So close...
