### ISSUE TITLE
[BUG] Atlassian domain verification `HTML` file in wrong directory

### ISSUE THREAD

**Issue by jbampton** [One-Language/Website#59]
**Describe the bug**

Needs to be in the `public` folder I think.

<img width="512" alt="Screen Shot 2021-07-29 at 2 45 56 am" src="https://user-images.githubusercontent.com/418747/127363385-cb39dd55-0309-405e-9aed-e6fcf19ffe8b.png">

**Comment by BaseMax** [comment]
Where is the `HTML` file right now?

**Comment by BaseMax** [comment]
I just see. `website/atlassian-domain-verification.html `

**Comment by BaseMax** [comment]
Fixed https://github.com/One-Language/Website/commit/51e2b2786568a7b35cf671f6cc4ac81c70c82b02

**Comment by BaseMax** [comment]
**alpha-version** branch connected to  github pages.
https://github.com/One-Language/Website/settings

**Comment by BaseMax** [comment]
fixed now: https://github.com/One-Language/Website/commit/7b372df3d0bff786814a2b3c3cf25e0561ee1e45

**Comment by BaseMax** [comment]
Done https://onelang.org/atlassian-domain-verification.html
